apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: helloworld-redis
    app.kubernetes.io/name: helloworld-redis
    app.kubernetes.io/version: 1.16.0
  name: redis
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: helloworld-redis
        app.kubernetes.io/name: helloworld-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.6-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379