apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: helloworld
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: helloworld
    helm.sh/chart: helloworld-0.1.0
  name: helloworld
  namespace: default
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld