apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: helloworld
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/version: 1.16.0
  name: helloworld-replacepathregex
  namespace: default
spec:
  replacePathRegex:
    regex: ^/helloworld/(.*)
    replacement: /$1