apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld
  namespace: default
spec:
  maxReplicas: 50
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld