FROM --platform=$BUILDPLATFORM golang:1.17 as builder

COPY ./ .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=$BUILDPLATFORM go build -v -o /app main.go

FROM alpine:3.15

WORKDIR /home/user/app/

COPY --from=builder /app .

CMD ["./app"]