FROM golang:1.17 as builder

COPY ./ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o /app.linux main.go

FROM alpine:3.15
WORKDIR /home/user/app/
COPY --from=builder /app.linux .
CMD ["./app.linux"]